[package]
name = "lucky"
version = "0.1.0"
edition = "2021"

[lib]
name = "lucky_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[[bin]]
name = "lucky"
path = "src/main.rs"

[dependencies]
tauri = { version = "2", features = [] }
tokio = { version = "1", features = ["net", "time"] }

[build-dependencies]
tauri-build = { version = "2", features = [] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
strip = true
opt-level = "s"
